### ISSUE TITLE
Adding custom tags to Azure Cloud Profile

### ISSUE THREAD

**Issue by jigyasapriyadarshini** [jenkinsci/azure-vm-agents-plugin#377]
Team I would like to add custom tags to the Azure Cloud Profile inside Jenkins. I was having a look at the https://github.com/jigyasapriyadarshini/azure-vm-agents-plugin/blob/master/src/main/java/com/microsoft/azure/vmagent/builders/AzureVMTemplateBuilder.java to find any relevant variable/ function that I could leverage. Can someone guide me if there is any way to do this via code?

![image](https://user-images.githubusercontent.com/20901180/209518768-c4da365d-d5ff-4b76-81a9-c1b046482964.png)

**Comment by timja** [comment]
The recommended approach is to use the configuration as code plugin and export the running config

https://github.com/jenkinsci/azure-vm-agents-plugin#configure-vm-template-using-configuration-as-code-plugin

Otherwise yes you can use the method that you leveraged the next section in the README has some code that would get you started on this
