### ISSUE TITLE
azure vm agents plugin doesn't uncached credential when updated

### ISSUE THREAD

**Issue by smerle33** [jenkinsci/azure-vm-agents-plugin#539]
### Jenkins and plugins versions report

on trusted.ci when I did the azure credential `Azure AD Application password ` https://github.com/jenkins-infra/helpdesk/issues/4107
We discovered that even after a save on the update credential, the plugin is still using the cached version. We had to restart the controller to make sure we use the new credential
as reminder, here is a first analyse from [tim](https://github.com/timja): https://github.com/jenkins-infra/helpdesk/issues/4107#issuecomment-2150237990

### What Operating System are you using (both controller, and any agents involved in the problem)?

trusted.ci 

### Reproduction steps

update a credential

### Expected Results

used of the new credential

### Actual Results

used of cached credential

**Comment by timja** [comment]
So I thought this worked, but that's probably because it takes so long to invalidate a credential.

I revoked it over 5 minutes ago and still >50% of the time it authenticates fine.

Pretty sure my analysis in the linked issue is right, but I'll wait till it fully fails, see that updating doesn't fix it and then make the change.

The cache expires after 24 hours so anyone updating the secret 24 hours or more ahead of time wouldn't be affected either.

**Comment by timja** [comment]
Hmm I can't reproduce this, I updated the secret and it worked just fine =/.

**Comment by smerle33** [comment]
sorry I didn't save the logs ...
